[workspace]
members = [
  "node"
]

[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-css"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
cssparser = "0.28.1"
cssparser-macros = "*"
selectors = "*"
indoc = "*"
itertools = "*"
smallvec = { version = "1.7.0", features = ["union"] }
bitflags = "*"
parcel_sourcemap = "2.0.0"

[profile.release]
lto = true
