[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-css"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
serde = { version = "1.0.123", features = ["derive"] }
serde_bytes = "0.11.5"
cssparser = "0.28.1"
cssparser-macros = "*"
selectors = "*"

[build-dependencies]
napi-build = { version = "1" }
