[workspace]
members = [
  "node"
]

[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel_css"
version = "1.0.0-alpha.6"
description = "A CSS parser, transformer, and minifier"
license = "MIT"
edition = "2018"
keywords = [ "CSS", "minifier", "Parcel" ]
repository = "https://github.com/parcel-bundler/parcel-css"

[features]
grid = []

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
cssparser = "0.28.1"
selectors = "0.23.0"
itertools = "0.10.1"
smallvec = { version = "1.7.0", features = ["union"] }
bitflags = "1.3.2"
parcel_sourcemap = "2.0.0"

[dev-dependencies]
indoc = "1.0.3"

[profile.release]
lto = true
