[workspace]
members = [
  "node"
]

[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel_css"
version = "1.0.0-alpha.5"
description = "A CSS parser, transformer, and minifier"
license = "MIT"
edition = "2018"
keywords = [ "CSS", "minifier", "Parcel" ]
repository = "https://github.com/parcel-bundler/parcel-css"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
cssparser = "0.28.1"
cssparser-macros = "*"
selectors = "*"
indoc = "*"
itertools = "*"
smallvec = { version = "1.7.0", features = ["union"] }
bitflags = "*"
parcel_sourcemap = "2.0.0"

[profile.release]
lto = true
