[workspace]
members = [
  "node",
  "selectors"
]

[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel_css"
version = "1.0.0-alpha.13"
description = "A CSS parser, transformer, and minifier"
license = "MPL-2.0"
edition = "2018"
keywords = [ "CSS", "minifier", "Parcel" ]
repository = "https://github.com/parcel-bundler/parcel-css"

[[bin]]
name = "parcel_css"
path = "src/main.rs"
required-features = ["cli"]

[lib]
name = "parcel_css"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
cssparser = "0.29.1"
parcel_selectors = { version = "0.24.0", path = "./selectors" }
itertools = "0.10.1"
smallvec = { version = "1.7.0", features = ["union"] }
bitflags = "1.3.2"
parcel_sourcemap = "2.0.0"
data-encoding = "2.3.2"
lazy_static = "1.4.0"
clap = { version = "3.0.6", features = ["derive"], optional = true }
retain_mut = "0.1.5"
serde_json = "*"
pathdiff = "0.2.1"

[dev-dependencies]
indoc = "1.0.3"
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"

[features]
default = ["cli", "grid"]
cli = ["clap"]
grid = []

[[test]]
name = "cli_integration_tests"
path = "tests/cli_integration_tests.rs"
required-features = ["cli"]

[profile.release]
lto = true
